version: '3'

services:
  griddyna-app:
    image: gridsuite/griddyna-app:latest
    ports:
      - 83:8080
    volumes:
      - ./dynamic-mapping/griddyna-app-idpSettings.json:/opt/bitnami/apache/htdocs/griddyna/idpSettings.json:Z
      - ./env.json:/opt/bitnami/apache/htdocs/griddyna/env.json:Z
    depends_on:
      - logspout

  dynamic-mapping-server:
    image: gridsuite/dynamic-mapping-server:latest
    ports:
      - 5036:80
    volumes:
      - $PWD/../../k8s/base/config/dynamic-mapping-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../../k8s/base/config/common-application.yml:/config/common/application.yml:Z
      - $PWD/../database.properties:/config/database.properties:Z
    restart:
      on-failure
    depends_on:
      - logspout
      - postgres
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx768m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0
