version: '3'

services:
  griddyna-app:
    image: gridsuite/griddyna-app:latest
    ports:
      - 83:80
    volumes:
      - $PWD/../griddyna-app-idpSettings.json:/usr/local/apache2/htdocs/griddyna/idpSettings.json:Z
      - $PWD/../env.json:/usr/local/apache2/htdocs/griddyna/env.json:Z
    depends_on:
      - logspout
    command: --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0

  dynamic-mapping-server:
    image: gridsuite/dynamic-mapping-server:latest
    ports:
      - 5036:80
    volumes:
      - $PWD/../../k8s/base/config/dynamic-mapping-server-application.yml:/config/application.yml:Z
      - $PWD/../database.properties:/config/database.properties:Z
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx128m
    command: --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0
