dynawo:
  homeDir: /dynaflow-launcher
  debug: true

dynawo-algorithms:
  homeDir: /dynaflow-launcher
  debug: true

# Nb of concurrent processes - should be in-sync with ds.run.dsGroup queue concurrency
computation-local:
  available-core: 2