hades2:
  homeDir: /hades2
  debug: false

dynaflow:
  homeDir: /dynaflow-launcher
  debug: false

#Workaround iidm in-memory impl present on classpath (needed by cvg-extension)
network:
  default-impl-name: NetworkStore

# Nb of hades2 concurrent processes - should be in-sync with sa.run.saGroup queue concurrency
computation-local:
  available-core: 2

open-security-analysis-default-parameters:
  threadCount: 8
