base-voltages-config:
  base-voltages-config-infos:
    - name: voltage-level-7
      min-value: 300
      max-value: 500
    - name: voltage-level-6
      min-value: 200
      max-value: 300
    - name: voltage-level-5
      min-value: 100
      max-value: 200
    - name: voltage-level-4
      min-value: 70
      max-value: 100
    - name: voltage-level-3
      min-value: 50
      max-value: 70
    - name: voltage-level-2
      min-value: 40
      max-value: 50
    - name: voltage-level-1
      min-value: 0
      max-value: 40
