network:
  default-impl-name: NetworkStore

# Nb of concurrent processes - should be in-sync with voltageinit.run.voltageinitGroup queue concurrency
computation-local:
  available-core: 2

import-export-parameters-default-value:
  iidm.export.ampl.export-version: "1.0"