apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-sa-worker-server
  labels:
    name: monitor-sa-worker-server
    version: "1"
    app.kubernetes.io/component: gridsuite-springboot
    gridsuite.org/springboot-with-database: "true"
    gridsuite.org/springboot-with-rabbitmq: "true"
  annotations:
    gridsuite.org/cpu: cpu-l
    gridsuite.org/memory: memory-xl
spec:
  selector:
    matchLabels:
      name: monitor-sa-worker-server
  template:
    metadata:
      labels:
        name: monitor-sa-worker-server
    spec:
      containers:
        - name: main
          image: docker.io/gridsuite/monitor-worker-server:latest
          volumeMounts:
            - mountPath: /config/specific
              name: monitor-sa-worker-server-configmap-specific-volume
            - mountPath: /home/powsybl/.itools
              name: monitor-sa-worker-server-itools-configmap-volume
      volumes:
        - name: monitor-sa-worker-server-configmap-specific-volume
          configMap:
            name: monitor-sa-worker-server-configmap-specific
        - name: monitor-sa-worker-server-itools-configmap-volume
          configMap:
            name: monitor-sa-worker-server-itools-configmap
