powsybl-ws:
  environment: integ_

  # cassandra database prefix
  cassandra:
    keyspace:
      prefix: ${powsybl-ws.environment:}

  # Postgres database prefix
  postgres:
    databaseOrSchema:
      prefix: ${powsybl-ws.environment:}

  # RabbitMQ binding destination prefixes
  rabbitmq:
    destination:
      prefix: ${powsybl-ws.environment:}

  # elasticsearch index prefixes
  elasticsearch:
    index:
      prefix: ${powsybl-ws.environment:}