apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cgmes-gl-server-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    # To be able to import big networks
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    # springfox swagger-ui uses X-Forwarded-Prefix to find the
    # base url when behind a reverse proxy.
    # nginx-ingress-controller V0.24 has a simple alternative
    # but latest minikube 1.1.0 uses V0.23 (untested):
    # nginx.ingress.kubernetes.io/x-forwarded-prefix: "/cgmes-gl-server"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Prefix         /cgmes-gl-server/;
spec:
  rules:
  - http:
      paths:
      - path: /cgmes-gl-server(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: cgmes-gl-server
            port:
              number: 80
