apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
 - ../../base

resources:
  - oidc-mock-server-deployment.yaml
  - oidc-mock-server-ingress.yaml
  - oidc-mock-server-service.yaml
  - rabbitmq-deployment.yaml
  - rabbitmq-ingress.yaml
  - rabbitmq-service.yaml
  - kibana-deployment.yaml
  - kibana-ingress.yaml
  - kibana-service.yaml
  - elasticsearch-deployment.yaml
  - elasticsearch-ingress.yaml
  - elasticsearch-service.yaml
  - case-server-ingress.yaml
  - case-validation-server-ingress.yaml
  - cgmes-boundary-server-ingress.yaml
  - cgmes-gl-server-ingress.yaml
  - geo-data-server-ingress.yaml
  - network-conversion-server-ingress.yaml
  - network-map-server-ingress.yaml
  - network-store-server-ingress.yaml
  - odre-server-ingress.yaml
  - single-line-diagram-server-ingress.yaml
  - network-modification-server-ingress.yaml
  - study-server-ingress.yaml
  - gateway-ingress.yaml
  - loadflow-server-ingress.yaml
  - balances-adjustment-server-ingress.yaml
  - notification-server-ingress.yaml
  - merge-orchestrator-server-ingress.yaml
  - merge-notification-server-ingress.yaml
  - actions-server-ingress.yaml
  - filter-server-ingress.yaml
  - report-server-ingress.yaml
  - security-analysis-server-ingress.yaml
  - config-server-ingress.yaml
  - config-notification-server-ingress.yaml
  - dynamic-simulation-server-ingress.yaml
  - directory-server-ingress.yaml
  - explore-server-ingress.yaml
  - external-cassandra-service.yaml
  - external-postgres-service.yaml
  - dynamic-mapping-server-ingress.yaml

configMapGenerator:
  - name: network-store-server-configmap
    files:
      - cassandra.properties

  - name: geo-data-server-configmap
    files:
      - cassandra.properties

  - name: study-server-configmap
    files:
      - database.properties

  - name: gridstudy-app-configmap
    files:
      - idpSettings.json=gridstudy-app-idpSettings.json

  - name: gridexplore-app-configmap
    files:
      - idpSettings.json=gridexplore-app-idpSettings.json

  - name: gridstudy-app-env-configmap
    files:
      - env.json=env.json

  - name: gridexplore-app-env-configmap
    files:
      - env.json=env.json

  - name: gridmerge-app-configmap
    files:
      - idpSettings.json=gridmerge-app-idpSettings.json

  - name: gridmerge-app-env-configmap
    files:
      - env.json=env.json

  - name: gateway-configmap
    files:
      - allowed-issuers.yml

  - name: case-import-job-configmap
    files:
      - config.yml=case-import-job-config.yml

  - name: merge-orchestrator-server-configmap
    files:
      - database.properties

  - name: kibana-configmap
    files:
      - kibana.yml

  - name: cgmes-boundary-server-configmap
    files:
      - cassandra.properties

  - name: cgmes-assembling-job-configmap
    files:
      - config.yml=cgmes-assembling-job-config.yml

  - name: actions-server-configmap
    files:
      - database.properties

  - name: filter-server-configmap
    files:
      - database.properties

  - name: report-server-configmap
    files:
      - database.properties

  - name: security-analysis-server-configmap
    files:
      - cassandra.properties

  - name: config-server-configmap
    files:
      - database.properties

  - name: dynamic-simulation-server-configmap
    files:
      - database.properties

  - name: directory-server-configmap
    files:
      - database.properties

  - name: cgmes-boundary-import-job-configmap
    files:
      - config.yml=cgmes-boundary-import-job-config.yml

  - name: network-modification-server-configmap
    files:
      - database.properties

  - name: dynamic-mapping-server-configmap
    files:
      - database.properties

  - name: griddyna-app-configmap
    files:
      - idpSettings.json=griddyna-app-idpSettings.json

  - name: griddyna-app-env-configmap
    files:
      - env.json=env.json
# common-application.yml config
  - name: case-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: case-validation-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: geo-data-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: network-conversion-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: network-map-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: network-store-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: single-line-diagram-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: network-modification-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: study-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: cgmes-gl-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: odre-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: gateway-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: loadflow-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: balances-adjustment-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: notification-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: merge-orchestrator-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: merge-notification-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: cgmes-boundary-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: actions-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: filter-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: report-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: security-analysis-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: config-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: config-notification-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: dynamic-simulation-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: directory-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: directory-notification-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  
  - name: explore-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml
  - name: dynamic-mapping-server-configmap-common
    behavior: merge
    files:
      - application.yml=common-application.yml