apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-mock-server
  labels:
    name: oidc-mock-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: oidc-mock-server
  template:
    metadata:
      labels:
        name: oidc-mock-server
    spec:
      containers:
      - name: oidc-mock-server
        image: docker.io/gridsuite/oidc-mock-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: DEBUG
          value: "oidc-provider:*"
        - name: CLIENT_COUNT
          value: "3"
        - name: CLIENT_ID
          value: "gridstudy-client"
        - name: CLIENT_REDIRECT_URI
          value: "http://<TO COMPLETE>/gridstudy/sign-in-callback"
        - name: CLIENT_LOGOUT_REDIRECT_URI
          value: "http://<TO COMPLETE>/gridstudy/logout-callback"
        - name: CLIENT_SILENT_REDIRECT_URI
          value: "http://<TO COMPLETE>/gridstudy/silent-renew-callback"
        - name: CLIENT_ID_2
          value: "gridmerge-client"
        - name: CLIENT_REDIRECT_URI_2
          value: "http://<TO COMPLETE>/gridmerge/sign-in-callback"
        - name: CLIENT_LOGOUT_REDIRECT_URI_2
          value: "http://<TO COMPLETE>/gridmerge/logout-callback"
        - name: CLIENT_SILENT_REDIRECT_URI_2
          value: "http://<TO COMPLETE>/gridmerge/silent-renew-callback"
        - name: CLIENT_ID_3
          value: "griddata-client"
        - name: CLIENT_REDIRECT_URI_3
          value: "http://<TO COMPLETE>/griddata/sign-in-callback"
        - name: CLIENT_LOGOUT_REDIRECT_URI_3
          value: "http://<TO COMPLETE>/griddata/logout-callback"
        - name: CLIENT_SILENT_REDIRECT_URI_3
          value: "http://<TO COMPLETE>/griddata/silent-renew-callback"
        - name: ISSUER_HOST
          value: "<TO COMPLETE>"
        - name: ISSUER_PREFIX
          value: "/oidc-mock-server"
      restartPolicy: Always
