include:
  - ../docker-compose.base.yml
  - ../technical/docker-compose.technical.yml
  - ../dynamic-mapping/docker-compose.dynamic-mapping.yml
  - ../study/docker-compose.study.yml
  - docker-compose.monitor.yml
