server:
  port: 80

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 103MB

  rabbitmq:
    addresses: rabbitmq
    port: 5672
    stream:
      bindings:
        publishCaseImport-out-0:
          destination: case.import
      source: publishCaseImport

  data:
    elasticsearch:
      enabled : true
      host: elasticsearch
      port: 9200
      index: case-server
      type: metadatas

case-store-directory: /cases
