server:
  port: 80

geo-data-server:
  base.url: http://geo-data-server/

backing-services:
  case:
    base-uri: http://case-server/
  study-server:
    base-uri: http://study-server/

logging:
  level:
    org.gridsuite.gateway: DEBUG
