apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-store-server
  labels:
    name: network-store-server
    version: "1"
    app.kubernetes.io/component: gridsuite-springboot
    gridsuite.org/springboot-with-database: "true"
  annotations:
    gridsuite.org/cpu: cpu-xxlarge
    gridsuite.org/memory: memory-xxl
spec:
  selector:
    matchLabels:
      name: network-store-server
  template:
    metadata:
      labels:
        name: network-store-server
    spec:
      containers:
      - name: main
        image: docker.io/powsybl/network-store-server:latest
        volumeMounts:
        - mountPath: /config/specific
          name: network-store-server-configmap-specific-volume
      volumes:
        - name: network-store-server-configmap-specific-volume
          configMap:
            name: network-store-server-configmap-specific
