version: '4.0'

services:
  griddyna-app:
    profiles:
      - all
      - suite
      - dynamic-mapping
      - dynamic-simulation
    image: gridsuite/griddyna-app:latest
    ports:
      - 83:8080
    volumes:
      - $PWD/griddyna-app-idpSettings.json:/opt/bitnami/apache/htdocs/griddyna/idpSettings.json:Z
      - $PWD/env.json:/opt/bitnami/apache/htdocs/griddyna/env.json:Z
    depends_on:
      - logspout

  dynamic-mapping-server:
    profiles:
      - all
      - suite
      - dynamic-mapping
      - dynamic-simulation
    image: gridsuite/dynamic-mapping-server:latest
    ports:
      - 5036:80
    volumes:
      - $PWD/../k8s/resources/dynamic-mapping/config/dynamic-mapping-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../k8s/resources/common/config/common-application.yml:/config/common/application.yml:Z
    restart: unless-stopped
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx768m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0
