- op: add
  path: /spec/template/spec/volumes/1/configMap/items
  value:
#TODO can we avoid repeating all keys here just to put openid-configuration in the .well-known folder??
    - key: apps-metadata.json
      path: apps-metadata.json
    - key: apps-metadata-base-voltages.json
      path: apps-metadata-base-voltages.json
    - key: version.json
      path: version.json
    - key: keys
      path: keys
    - key: openid-configuration
      path: .well-known/openid-configuration
