server:
  port: 80
  servlet:
    context-path: /


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  application:
    name: network-conversion-server
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 103MB

network-store-server:
  preloading-strategy: COLLECTION
  base-uri: http://network-store-server

backing-services:
  case-server:
    base-uri: http://case-server
  geo-data-server:
    base-uri: http://geo-data-server

