version: '4.0'

services:
  merge-orchestrator-server:
    profiles:
      - all
      - merging
      - suite
    image: gridsuite/merge-orchestrator-server:latest
    ports:
      - 5020:80
    volumes:
      - $PWD/../../k8s/resources/merging/config/merge-orchestrator-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../../k8s/resources/common/config/common-application.yml:/config/common/application.yml:Z
    restart: unless-stopped
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx576m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0
    memswap_limit: 1g
    deploy:
      resources:
        limits:
          memory: 1g

  merge-notification-server:
    profiles:
      - all
      - merging
      - suite
    image: gridsuite/merge-notification-server:latest
    ports:
      - 5002:80
    volumes:
      - $PWD/../../k8s/resources/merging/config/merge-notification-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../../k8s/resources/common/config/common-application.yml:/config/common/application.yml:Z
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx96m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0
    memswap_limit: 384m
    deploy:
      resources:
        limits:
          memory: 384m

  balances-adjustment-server:
    profiles:
      - all
      - merging
      - suite
    image: gridsuite/balances-adjustment-server:latest
    ports:
      - 5010:80
    volumes:
      - $PWD/../../k8s/resources/merging/config/balances-adjustment-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../../k8s/resources/common/config/common-application.yml:/config/common/application.yml:Z
      - $PWD/../../k8s/resources/merging/config/balances-adjustment-server-config.yml:/home/powsybl/.itools/config.yml:Z
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx576m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0
    memswap_limit: 1g
    deploy:
      resources:
        limits:
          memory: 1g

  case-validation-server:
    profiles:
      - all
      - merging
      - suite
    image: gridsuite/case-validation-server:latest
    ports:
      - 5011:80
    volumes:
      - $PWD/../../k8s/resources/merging/config/case-validation-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../../k8s/resources/common/config/common-application.yml:/config/common/application.yml:Z
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx96m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0
    memswap_limit: 384m
    deploy:
      resources:
        limits:
          memory: 384m

  cgmes-boundary-server:
    profiles:
      - all
      - merging
      - suite
    image: gridsuite/cgmes-boundary-server:latest
    ports:
      - 5021:80
    volumes:
      - $PWD/../../k8s/resources/merging/config/cgmes-boundary-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../../k8s/resources/common/config/common-application.yml:/config/common/application.yml:Z
    restart: unless-stopped
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx96m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0
    memswap_limit: 384m
    deploy:
      resources:
        limits:
          memory: 384m

  case-import-job:
    profiles:
      - all
      - merging
      - suite
    build:
      context: $PWD/../merging/case-import-job
      args:
        - http_proxy=${http_proxy-}
        - https_proxy=${https_proxy-}
        - no_proxy=${no_proxy-}
    volumes:
      - $PWD/../merging/case-import-job/job-crontab:/root/job-crontab:Z
      - $PWD/../../k8s/resources/merging/config/case-import-job-application.yml:/config/specific/application.yml:Z
      - $PWD/../merging/case-import-job/case-import-job-config.yml:/root/.itools/config.yml:Z
      - $PWD/../../k8s/resources/common/config/common-application.yml:/config/common/application.yml:Z
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0

  cgmes-assembling-job:
    profiles:
      - all
      - merging
      - suite
    build:
      context: $PWD/../merging/cgmes-assembling-job
      args:
        - http_proxy=${http_proxy-}
        - https_proxy=${https_proxy-}
        - no_proxy=${no_proxy-}
    volumes:
      - $PWD/../merging/cgmes-assembling-job/job-crontab:/root/job-crontab:Z
      - $PWD/../../k8s/resources/merging/config/cgmes-assembling-job-application.yml:/config/specific/application.yml:Z
      - $PWD/../merging/cgmes-assembling-job/cgmes-assembling-job-config.yml:/root/.itools/config.yml:Z
      - $PWD/../../k8s/resources/common/config/common-application.yml:/config/common/application.yml:Z
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0

  gridmerge-app:
    profiles:
      - all
      - merging
      - suite
    image: gridsuite/gridmerge-app:latest
    ports:
      - 81:8080
    volumes:
      - $PWD/../merging/gridmerge-app-idpSettings.json:/opt/bitnami/apache/htdocs/gridmerge/idpSettings.json:Z
      - $PWD/../env.json:/opt/bitnami/apache/htdocs/gridmerge/env.json:Z
    memswap_limit: 128m
    deploy:
      resources:
        limits:
          memory: 128m

  cgmes-boundary-import-job:
    profiles:
      - all
      - merging
      - suite
    build:
      context: $PWD/../merging/cgmes-boundary-import-job
      args:
        - http_proxy=${http_proxy-}
        - https_proxy=${https_proxy-}
        - no_proxy=${no_proxy-}
    volumes:
      - $PWD/../merging/cgmes-boundary-import-job/job-crontab:/root/job-crontab:Z
      - $PWD/../merging/cgmes-boundary-import-job/cgmes-boundary-import-job-config.yml:/root/.itools/config.yml:Z
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0
