version: '3'

services:

  merge-orchestrator-server:
    image: gridsuite/merge-orchestrator-server:latest
    ports:
      - 5020:80
    volumes:
      - $PWD/../../k8s/base/config/merge-orchestrator-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../../k8s/base/config/common-application.yml:/config/common/application.yml:Z
      - $PWD/../database.properties:/config/database.properties:Z
    restart:
      on-failure
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx768m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0

  merge-notification-server:
    image: gridsuite/merge-notification-server:latest
    ports:
      - 5002:80
    volumes:
      - $PWD/../../k8s/base/config/merge-notification-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../../k8s/base/config/common-application.yml:/config/common/application.yml:Z
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx128m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0

  balances-adjustment-server:
    image: gridsuite/balances-adjustment-server:latest
    ports:
      - 5010:80
    volumes:
      - $PWD/../../k8s/base/config/balances-adjustment-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../../k8s/base/config/common-application.yml:/config/common/application.yml:Z
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx768m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0

  case-validation-server:
    image: gridsuite/case-validation-server:latest
    ports:
      - 5011:80
    volumes:
      - $PWD/../../k8s/base/config/case-validation-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../../k8s/base/config/common-application.yml:/config/common/application.yml:Z
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx128m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0

  cgmes-boundary-server:
    image: gridsuite/cgmes-boundary-server:latest
    ports:
      - 5021:80
    volumes:
      - $PWD/../../k8s/base/config/cgmes-boundary-server-application.yml:/config/specific/application.yml:Z
      - $PWD/../../k8s/base/config/common-application.yml:/config/common/application.yml:Z
      - $PWD/../database.properties:/config/database.properties:Z
    restart:
      on-failure
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx128m
    command: --server.port=80 --spring.config.additional-location=/config/
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0

  case-import-job:
    build:
      context: merging/case-import-job
      args:
        - http_proxy=${http_proxy-}
        - https_proxy=${https_proxy-}
        - no_proxy=${no_proxy-}
    volumes:
      - $PWD/../merging/case-import-job/job-crontab:/root/job-crontab:Z
      - $PWD/../merging/case-import-job/case-import-job-config.yml:/root/.itools/config.yml:Z
    depends_on:
      - logspout
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0

  cgmes-assembling-job:
    build:
      context: merging/cgmes-assembling-job
      args:
        - http_proxy=${http_proxy-}
        - https_proxy=${https_proxy-}
        - no_proxy=${no_proxy-}
    volumes:
      - $PWD/../merging/cgmes-assembling-job/job-crontab:/root/job-crontab:Z
      - $PWD/../merging/cgmes-assembling-job/cgmes-assembling-job-config.yml:/root/.itools/config.yml:Z
    depends_on:
      - logspout
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0

  gridmerge-app:
    image: gridsuite/gridmerge-app:latest
    ports:
      - 81:8080
    volumes:
      - $PWD/../merging/gridmerge-app-idpSettings.json:/opt/bitnami/apache/htdocs/gridmerge/idpSettings.json:Z
      - $PWD/../env.json:/opt/bitnami/apache/htdocs/gridmerge/env.json:Z
    depends_on:
      - logspout

  cgmes-boundary-import-job:
    build:
      context: merging/cgmes-boundary-import-job
      args:
        - http_proxy=${http_proxy-}
        - https_proxy=${https_proxy-}
        - no_proxy=${no_proxy-}
    volumes:
      - $PWD/../merging/cgmes-boundary-import-job/job-crontab:/root/job-crontab:Z
      - $PWD/../merging/cgmes-boundary-import-job/cgmes-boundary-import-job-config.yml:/root/.itools/config.yml:Z
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # for docker < 20.03.0
