version: '3'

services:

  merge-orchestrator-server:
    image: gridsuite/merge-orchestrator-server:latest
    ports:
      - 5020:80
    volumes:
      - $PWD/../../k8s/base/config/merge-orchestrator-server-application.yml:/config/application.yml:Z
      - $PWD/../cassandra.properties:/config/cassandra.properties:Z
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx768m

  merge-notification-server:
    image: gridsuite/merge-notification-server:latest
    ports:
      - 5002:80
    volumes:
      - $PWD/../../k8s/base/config/merge-notification-server-application.yml:/config/application.yml:Z
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx128m

  balances-adjustment-server:
    image: gridsuite/balances-adjustment-server:latest
    ports:
      - 5010:80
    volumes:
      - $PWD/../../k8s/base/config/balances-adjustment-server-application.yml:/config/application.yml:Z
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx768m

  case-validation-server:
    image: gridsuite/case-validation-server:latest
    ports:
      - 5011:80
    volumes:
      - $PWD/../../k8s/base/config/case-validation-server-application.yml:/config/application.yml:Z
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx128m

  cgmes-boundary-server:
    image: gridsuite/cgmes-boundary-server:latest
    ports:
      - 5021:80
    volumes:
      - $PWD/../../k8s/base/config/cgmes-boundary-server-application.yml:/config/application.yml:Z
      - $PWD/../cassandra.properties:/config/cassandra.properties:Z
    depends_on:
      - logspout
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx128m

  case-import-job:
    build: case-import-job
    volumes:
      - $PWD/../case-import-job/job-crontab:/root/job-crontab:Z
      - $PWD/../case-import-job/case-import-job-config.yml:/root/.itools/config.yml:Z
    depends_on:
      - logspout

  cgmes-assembling-job:
    build: merging/cgmes-assembling-job
    volumes:
      - $PWD/cgmes-assembling-job/job-crontab:/root/job-crontab:Z
      - $PWD/cgmes-assembling-job/cgmes-assembling-job-config.yml:/root/.itools/config.yml:Z
    depends_on:
      - logspout

  gridmerge-app:
    image: gridsuite/gridmerge-app:latest
    ports:
      - 81:80
    volumes:
      - $PWD/../gridmerge-app-idpSettings.json:/usr/local/apache2/htdocs/gridmerge/idpSettings.json:Z
      - $PWD/../env.json:/usr/local/apache2/htdocs/gridmerge/env.json:Z
    depends_on:
      - logspout

  cgmes-boundary-import-job:
    build: cgmes-boundary-import-job
    volumes:
      - $PWD/../cgmes-boundary-import-job/job-crontab:/root/job-crontab:Z
      - $PWD/../cgmes-boundary-import-job/cgmes-boundary-import-job-config.yml:/root/.itools/config.yml:Z

