apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../azure-commons

configMapGenerator:
  - name: gridstudy-app-configmap
    files:
      - idpSettings.json=gridstudy-app-idpSettings.json
  - name: gridstudy-app-env-configmap
    files:
      - env.json=env.json
  - name: gridmerge-app-configmap
    files:
      - idpSettings.json=gridmerge-app-idpSettings.json
  - name: gridmerge-app-env-configmap
    files:
      - env.json=env.json
  - name: griddata-app-configmap
    files:
      - idpSettings.json=griddata-app-idpSettings.json
  - name: griddata-app-env-configmap
    files:
      - env.json=env.json

# Patch ingress host
patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: gridstudy-app-ingress
    path: patch_tls_ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: gridstudy-app-ingress
    path: patch_ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: gridmerge-app-ingress
    path: patch_tls_ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: gridmerge-app-ingress
    path: patch_ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: griddata-app-ingress
    path: patch_tls_ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: griddata-app-ingress
    path: patch_ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: apps-metadata-server-ingress
    path: patch_tls_ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: apps-metadata-server-ingress
    path: patch_ingress.yaml
