apiVersion: apps/v1
kind: Deployment
metadata:
  name: balances-adjustment-server
  labels:
    name: balances-adjustment-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: balances-adjustment-server
  template:
    metadata:
      labels:
        name: balances-adjustment-server
    spec:
      containers:
        - name: balances-adjustment-server
          image: docker.io/gridsuite/balances-adjustment-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /config
              name: balances-adjustment-server-configmap-volume
          resources:
            requests:
              memory: "384Mi"
            limits:
              memory: "384Mi"
          args: ["--spring.config.additional-location=/config/"]
      restartPolicy: Always
      volumes:
        - name: balances-adjustment-server-configmap-volume
          configMap:
            name: balances-adjustment-server-configmap
