apiVersion: apps/v1
kind: Deployment
metadata:
  name: balances-adjustment-server
  labels:
    name: balances-adjustment-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: balances-adjustment-server
  template:
    metadata:
      labels:
        name: balances-adjustment-server
    spec:
      containers:
        - name: balances-adjustment-server
          image: docker.io/gridsuite/balances-adjustment-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /config
              name: balances-adjustment-server-configmap-volume
            - mountPath: /tmp
              name: tmp-emptydir
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "256Mi"
      restartPolicy: Always
      volumes:
        - name: balances-adjustment-server-configmap-volume
          configMap:
            name: balances-adjustment-server-configmap
        - name: tmp-emptydir
          emptyDir: {}
