apiVersion: apps/v1
kind: Deployment
metadata:
  name: case-validation-server
  labels:
    app: gridsuite
    name: case-validation-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: case-validation-server
  template:
    metadata:
      labels:
        app: gridsuite
        name: case-validation-server
    spec:
      containers:
      - name: case-validation-server
        image: docker.io/gridsuite/case-validation-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /config
          name: case-validation-server-configmap-volume
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "256Mi"
      restartPolicy: Always
      volumes:
        - name: case-validation-server-configmap-volume
          configMap:
            name: case-validation-server-configmap
