apiVersion: apps/v1
kind: Deployment
metadata:
  name: gridstudy-app
  labels:
    app: gridsuite
    name: gridstudy-app
    version: "1"
spec:
  selector:
    matchLabels:
      name: gridstudy-app
  template:
    metadata:
      labels:
        app: gridsuite
        name: gridstudy-app
    spec:
      containers:
      - name: gridstudy-app
        image: docker.io/gridsuite/gridstudy-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs/gridstudy/idpSettings.json
          subPath: idpSettings.json
          name: gridstudy-app-configmap-volume
        - mountPath: /usr/local/apache2/htdocs/gridstudy/env.json
          subPath: env.json
          name: gridstudy-app-env-configmap-volume
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "128Mi"
      restartPolicy: Always
      volumes:
        - name: gridstudy-app-configmap-volume
          configMap:
            name: gridstudy-app-configmap
        - name: gridstudy-app-env-configmap-volume
          configMap:
            name: gridstudy-app-env-configmap
