apiVersion: apps/v1
kind: Deployment
metadata:
  name: gridstudy-app
  labels:
    name: gridstudy-app
    version: "1"
spec:
  selector:
    matchLabels:
      name: gridstudy-app
  template:
    metadata:
      labels:
        name: gridstudy-app
    spec:
      containers:
      - name: gridstudy-app
        image: docker.io/gridsuite/gridstudy-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/bitnami/apache/htdocs/gridstudy/idpSettings.json
          subPath: idpSettings.json
          name: gridstudy-app-configmap-volume
        - mountPath: /opt/bitnami/apache/htdocs/gridstudy/env.json
          subPath: env.json
          name: gridstudy-app-env-configmap-volume
        - mountPath: /opt/bitnami/apache/var/run/
          name: run-emptydir
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "128Mi"
      restartPolicy: Always
      volumes:
        - name: gridstudy-app-configmap-volume
          configMap:
            name: gridstudy-app-configmap
        - name: gridstudy-app-env-configmap-volume
          configMap:
            name: gridstudy-app-env-configmap
        - name: run-emptydir
          emptyDir: {}
