apiVersion: apps/v1
kind: Deployment
metadata:
  name: gridmerge-app
  labels:
    name: gridmerge-app
    version: "1"
spec:
  selector:
    matchLabels:
      name: gridmerge-app
  template:
    metadata:
      labels:
        name: gridmerge-app
    spec:
      containers:
      - name: gridmerge-app
        image: docker.io/gridsuite/gridmerge-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs/gridmerge/idpSettings.json
          subPath: idpSettings.json
          name: gridmerge-app-configmap-volume
        - mountPath: /usr/local/apache2/htdocs/gridmerge/env.json
          subPath: env.json
          name: gridmerge-app-env-configmap-volume
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "128Mi"
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
      restartPolicy: Always
      volumes:
        - name: gridmerge-app-configmap-volume
          configMap:
            name: gridmerge-app-configmap
        - name: gridmerge-app-env-configmap-volume
          configMap:
            name: gridmerge-app-env-configmap
