apiVersion: apps/v1
kind: Deployment
metadata:
  name: gridactions-app
  labels:
    name: gridactions-app
    version: "1"
spec:
  selector:
    matchLabels:
      name: gridactions-app
  template:
    metadata:
      labels:
        name: gridactions-app
    spec:
      containers:
      - name: gridactions-app
        image: docker.io/gridsuite/gridactions-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/bitnami/apache/htdocs/gridactions/idpSettings.json
          subPath: idpSettings.json
          name: gridactions-app-configmap-volume
        - mountPath: /opt/bitnami/apache/htdocs/gridactions/env.json
          subPath: env.json
          name: gridactions-app-env-configmap-volume
        - mountPath: /opt/bitnami/apache/var/run/
          name: run-emptydir
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "128Mi"
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
      restartPolicy: Always
      volumes:
        - name: gridactions-app-configmap-volume
          configMap:
            name: gridactions-app-configmap
        - name: gridactions-app-env-configmap-volume
          configMap:
            name: gridactions-app-env-configmap
        - name: run-emptydir
          emptyDir: {}
