apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: demo

resources:
  - case-server-claim.yaml
  - case-server-deployment.yaml
  - case-server-ingress.yaml
  - case-server-service.yaml
  - cgmes-gl-server-deployment.yaml
  - cgmes-gl-server-ingress.yaml
  - cgmes-gl-server-service.yaml
  - geo-data-server-deployment.yaml
  - geo-data-server-ingress.yaml
  - geo-data-server-service.yaml
  - network-conversion-server-deployment.yaml
  - network-conversion-server-ingress.yaml
  - network-conversion-server-service.yaml
  - network-map-server-deployment.yaml
  - network-map-server-ingress.yaml
  - network-map-server-service.yaml
  - network-store-server-deployment.yaml
  - network-store-server-ingress.yaml
  - network-store-server-service.yaml
  - odre-server-deployment.yaml
  - odre-server-ingress.yaml
  - odre-server-service.yaml
  - single-line-diagram-server-deployment.yaml
  - single-line-diagram-server-ingress.yaml
  - single-line-diagram-server-service.yaml
  - study-app-deployment.yaml
  - study-app-ingress.yaml
  - study-app-service.yaml
  - study-server-deployment.yaml
  - study-server-ingress.yaml
  - study-server-service.yaml

configMapGenerator:
  - name: case-server-configmap
    files:
      - application.yml=config/case-server-application.yml
  - name: geo-data-server-configmap
    files:
      - application.yml=config/geo-data-server-application.yml
  - name: network-conversion-server-configmap
    files:
      - application.yml=config/network-conversion-server-application.yml
  - name: network-map-server-configmap
    files:
      - application.yml=config/network-map-server-application.yml
  - name: network-store-server-configmap
    files:
      - application.yml=config/network-store-server-application.yml
  - name: single-line-diagram-server-configmap
    files:
      - application.yml=config/single-line-diagram-server-application.yml
  - name: study-server-configmap
    files:
      - application.yml=config/study-server-application.yml
  - name: cgmes-gl-server-configmap
    files:
      - application.yml=config/cgmes-gl-server-application.yml
  - name: odre-server-configmap
    files:
      - application.yml=config/odre-server-application.yml
