apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: demo

resources:
  - root-ingress.yaml
  - case-server-claim.yaml
  - case-server-deployment.yaml
  - case-server-service.yaml
  - case-validation-server-deployment.yaml
  - case-validation-server-service.yaml
  - cgmes-gl-server-deployment.yaml
  - cgmes-gl-server-service.yaml
  - geo-data-server-deployment.yaml
  - geo-data-server-service.yaml
  - network-conversion-server-deployment.yaml
  - network-conversion-server-service.yaml
  - network-map-server-deployment.yaml
  - network-map-server-service.yaml
  - network-store-server-deployment.yaml
  - network-store-server-service.yaml
  - odre-server-deployment.yaml
  - odre-server-service.yaml
  - single-line-diagram-server-deployment.yaml
  - single-line-diagram-server-service.yaml
  - network-modification-server-deployment.yaml
  - network-modification-server-service.yaml
  - gridmerge-app-deployment.yaml
  - gridmerge-app-ingress.yaml
  - gridmerge-app-service.yaml
  - gridexplore-app-deployment.yaml
  - gridexplore-app-ingress.yaml
  - gridexplore-app-service.yaml
  - gridstudy-app-deployment.yaml
  - gridstudy-app-ingress.yaml
  - gridstudy-app-service.yaml
  - study-server-deployment.yaml
  - study-server-service.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - loadflow-server-deployment.yaml
  - loadflow-server-service.yaml
  - balances-adjustment-server-deployment.yaml
  - balances-adjustment-server-service.yaml
  - notification-server-deployment.yaml
  - notification-server-service.yaml
  - case-import-cronjob.yaml
  - merge-orchestrator-server-deployment.yaml
  - merge-orchestrator-server-service.yaml
  - fluentd-service-account.yaml
  - fluentd-daemonset.yaml
  - fluentd-cluster-role-binding.yaml
  - fluentd-cluster-role.yaml
  - merge-notification-server-deployment.yaml
  - merge-notification-server-service.yaml
  - cgmes-boundary-server-deployment.yaml
  - cgmes-boundary-server-service.yaml
  - cgmes-assembling-cronjob.yaml
  - actions-server-deployment.yaml
  - actions-server-service.yaml
  - filter-server-deployment.yaml
  - filter-server-service.yaml
  - report-server-deployment.yaml
  - report-server-service.yaml
  - gridactions-app-deployment.yaml
  - gridactions-app-ingress.yaml
  - gridactions-app-service.yaml
  - apps-metadata-server-deployment.yaml
  - apps-metadata-server-service.yaml
  - apps-metadata-server-ingress.yaml
  - security-analysis-server-deployment.yaml
  - security-analysis-server-service.yaml
  - config-server-deployment.yaml
  - config-server-service.yaml
  - config-notification-server-deployment.yaml
  - config-notification-server-service.yaml
  - dynamic-simulation-server-deployment.yaml
  - dynamic-simulation-server-service.yaml
  - directory-server-deployment.yaml
  - directory-server-service.yaml
  - cgmes-boundary-import-cronjob.yaml
  - directory-notification-server-deployment.yaml
  - directory-notification-server-service.yaml

configMapGenerator:
  - name: case-server-configmap
    files:
      - application-default.yml=config/case-server-application.yml
      - application.yml=config/common-application.yml
  - name: case-validation-server-configmap
    files:
      - application-default.yml=config/case-validation-server-application.yml
      - application.yml=config/common-application.yml
  - name: geo-data-server-configmap
    files:
      - application-default.yml=config/geo-data-server-application.yml
      - application.yml=config/common-application.yml
  - name: network-conversion-server-configmap
    files:
      - application-default.yml=config/network-conversion-server-application.yml
      - application.yml=config/common-application.yml
  - name: network-conversion-server-itools-configmap
    files:
      - config.yml=config/network-conversion-server-config.yml
  - name: network-map-server-configmap
    files:
      - application-default.yml=config/network-map-server-application.yml
      - application.yml=config/common-application.yml
  - name: network-store-server-configmap
    files:
      - application-default.yml=config/network-store-server-application.yml
      - application.yml=config/common-application.yml
  - name: single-line-diagram-server-configmap
    files:
      - application-default.yml=config/single-line-diagram-server-application.yml
      - application.yml=config/common-application.yml
  - name: network-modification-server-configmap
    files:
      - application-default.yml=config/network-modification-server-application.yml
      - application.yml=config/common-application.yml
  - name: study-server-configmap
    files:
      - application-default.yml=config/study-server-application.yml
      - application.yml=config/common-application.yml
  - name: cgmes-gl-server-configmap
    files:
      - application-default.yml=config/cgmes-gl-server-application.yml
      - application.yml=config/common-application.yml
  - name: odre-server-configmap
    files:
      - application-default.yml=config/odre-server-application.yml
      - application.yml=config/common-application.yml
  - name: gateway-configmap
    files:
      - application-default.yml=config/gateway-application.yml
      - application.yml=config/common-application.yml
  - name: loadflow-server-configmap
    files:
      - application-default.yml=config/loadflow-server-application.yml
      - application.yml=config/common-application.yml
  - name: loadflow-server-itools-configmap
    files:
      - config.yml=config/loadflow-server-config.yml
  - name: balances-adjustment-server-configmap
    files:
      - application-default.yml=config/balances-adjustment-server-application.yml
      - application.yml=config/common-application.yml
  - name: notification-server-configmap
    files:
      - application-default.yml=config/notification-server-application.yml
      - application.yml=config/common-application.yml
  - name: merge-orchestrator-server-configmap
    files:
      - application-default.yml=config/merge-orchestrator-server-application.yml
      - application.yml=config/common-application.yml
  - name: merge-notification-server-configmap
    files:
      - application-default.yml=config/merge-notification-server-application.yml
      - application.yml=config/common-application.yml
  - name: cgmes-boundary-server-configmap
    files:
      - application-default.yml=config/cgmes-boundary-server-application.yml
      - application.yml=config/common-application.yml
  - name: actions-server-configmap
    files:
      - application-default.yml=config/actions-server-application.yml
      - application.yml=config/common-application.yml
  - name: filter-server-configmap
    files:
      - application-default.yml=config/filter-server-application.yml
      - application.yml=config/common-application.yml
  - name: report-server-configmap
    files:
      - application-default.yml=config/report-server-application.yml
      - application.yml=config/common-application.yml
  - name: apps-metadata-server-configmap
    files:
      - config/apps-metadata.json
  - name: security-analysis-server-configmap
    files:
      - application-default.yml=config/security-analysis-server-application.yml
      - application.yml=config/common-application.yml
  - name: security-analysis-server-itools-configmap
    files:
      - config.yml=config/security-analysis-server-config.yml
  - name: config-server-configmap
    files:
      - application-default.yml=config/config-server-application.yml
      - application.yml=config/common-application.yml
  - name: config-notification-server-configmap
    files:
      - application-default.yml=config/config-notification-server-application.yml
      - application.yml=config/common-application.yml
  - name: dynamic-simulation-server-configmap
    files:
      - application-default.yml=config/dynamic-simulation-server-application.yml
      - application.yml=config/common-application.yml
  - name: dynawo-config-configmap
    files:
      - models.par=config/dynamic-simulation/models.par
      - network.par=config/dynamic-simulation/network.par
      - solvers.par=config/dynamic-simulation/solvers.par
  - name: dynawo-itools-configmap
    files:
      - config.yml=config/dynawo-itools-config.yml
  - name: directory-server-configmap
    files:
      - application-default.yml=config/directory-server-application.yml
      - application.yml=config/common-application.yml
  - name: directory-notification-server-configmap
    files:
      - application-default.yml=config/directory-notification-server-application.yml
      - application.yml=config/common-application.yml
