apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadflow-server
  labels:
    name: loadflow-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: loadflow-server
  template:
    metadata:
      labels:
        name: loadflow-server
    spec:
      containers:
      - name: loadflow-server
        image: docker.io/gridsuite/loadflow-server:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /config
          name: loadflow-server-configmap-volume
        - mountPath: /home/powsybl/.itools
          name: loadflow-server-itools-configmap-volume
        - mountPath: /tmp
          name: tmp-emptydir
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "1Gi"
        args: ["--spring.config.additional-location=/config/"]
      restartPolicy: Always
      volumes:
        - name: loadflow-server-configmap-volume
          configMap:
            name: loadflow-server-configmap
        - name: loadflow-server-itools-configmap-volume
          configMap:
            name: loadflow-server-itools-configmap
        - name: tmp-emptydir
          emptyDir: {}
