apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-store-server
  labels:
    name: network-store-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: network-store-server
  template:
    metadata:
      labels:
        name: network-store-server
    spec:
      containers:
      - name: network-store-server
        image: docker.io/powsybl/network-store-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /config
          name: network-store-server-configmap-volume
        resources:
          requests:
            memory: "512Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100m"
      restartPolicy: Always
      volumes:
        - name: network-store-server-configmap-volume
          configMap:
            name: network-store-server-configmap
