apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-server
  labels:
    name: notification-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: notification-server
  template:
    metadata:
      labels:
        name: notification-server
    spec:
      containers:
      - name: notification-server
        image: docker.io/gridsuite/notification-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /config
          name: notification-server-configmap-volume
        - mountPath: /tmp
          name: tmp-emptydir
        - mountPath: /?
          name: app-emptydir
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "256Mi"
      restartPolicy: Always
      volumes:
        - name: notification-server-configmap-volume
          configMap:
            name: notification-server-configmap
        - name: tmp-emptydir
          emptyDir: {}
        - name: app-emptydir
          emptyDir: {}