apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-server
  labels:
    app: gridsuite
    name: notification-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: notification-server
  template:
    metadata:
      labels:
        app: gridsuite
        name: notification-server
    spec:
      containers:
      - name: notification-server
        image: docker.io/gridsuite/notification-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /config
          name: notification-server-configmap-volume
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "256Mi"
      restartPolicy: Always
      volumes:
        - name: notification-server-configmap-volume
          configMap:
            name: notification-server-configmap
