apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-analysis-server
  labels:
    name: security-analysis-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: security-analysis-server
  template:
    metadata:
      labels:
        name: security-analysis-server
    spec:
      containers:
        - name: security-analysis-server
          image: docker.io/gridsuite/security-analysis-server:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: JAVA_TOOL_OPTIONS
            value: "-XX:MaxRAMPercentage=50"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /config/common
              name: security-analysis-server-configmap-common-volume
            - mountPath: /config/specific
              name: security-analysis-server-configmap-specific-volume
            - mountPath: /home/powsybl/.itools
              name: security-analysis-server-itools-configmap-volume
            - mountPath: /tmp
              name: tmp-emptydir
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "1.5Gi"
            limits:
              memory: "1.5Gi"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
          args: ["--spring.config.additional-location=/config/"]
      restartPolicy: Always
      volumes:
        - name: security-analysis-server-configmap-common-volume
          configMap:
            name: security-analysis-server-configmap-common
        - name: security-analysis-server-configmap-specific-volume
          configMap:
            name: security-analysis-server-configmap-specific
        - name: security-analysis-server-itools-configmap-volume
          configMap:
            name: security-analysis-server-itools-configmap
        - name: tmp-emptydir
          emptyDir: {}
