apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-analysis-server
  labels:
    name: security-analysis-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: security-analysis-server
  template:
    metadata:
      labels:
        name: security-analysis-server
    spec:
      containers:
        - name: security-analysis-server
          image: docker.io/gridsuite/security-analysis-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /config
              name: security-analysis-server-configmap-volume
            - mountPath: /root/.itools
              name: security-analysis-server-itools-configmap-volume
          resources:
            requests:
              memory: "384Mi"
            limits:
              memory: "384Mi"
      restartPolicy: Always
      volumes:
        - name: security-analysis-server-configmap-volume
          configMap:
            name: security-analysis-server-configmap
        - name: security-analysis-server-itools-configmap-volume
          configMap:
            name: security-analysis-server-itools-configmap
