apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-analysis-server
  labels:
    name: security-analysis-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: security-analysis-server
  template:
    metadata:
      labels:
        name: security-analysis-server
    spec:
      containers:
        - name: security-analysis-server
          image: docker.io/gridsuite/security-analysis-server:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: JAVA_TOOL_OPTIONS
            value: "-XX:MaxRAMPercentage=50"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /config
              name: security-analysis-server-configmap-volume
            - mountPath: /?/.itools
              name: security-analysis-server-itools-configmap-volume
            - mountPath: /tmp
              name: tmp-emptydir
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "1.5Gi"
            limits:
              memory: "1.5Gi"
      restartPolicy: Always
      volumes:
        - name: security-analysis-server-configmap-volume
          configMap:
            name: security-analysis-server-configmap
        - name: security-analysis-server-itools-configmap-volume
          configMap:
            name: security-analysis-server-itools-configmap
        - name: tmp-emptydir
          emptyDir: {}
