services:

  rabbitmq:
    image: rabbitmq:4.0.4-management
    ports:
      - 15672:15672
      - 5672:5672
      - 15692:15692
    depends_on:
      logspout:
        condition: "service_started"
        required: false
    restart: unless-stopped

  postgres:
    build:
      context: ./
      dockerfile: Dockerfile-postgres
      args:
        - http_proxy=${http_proxy-}
        - https_proxy=${https_proxy-}
        - no_proxy=${no_proxy-}
    ports:
      - "5432:5432"
    command: "/init-databases.sh
              -c listen_addresses='*'
              -c shared_preload_libraries='auto_explain'
              -c auto_explain.log_min_duration=0
              -c jit=false
              -c enable_seqscan=false
              "
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DEFAULT_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - $GRIDSUITE_DATABASES/postgres/data:/var/lib/postgresql/data:Z
      - $GRIDSUITE_DATABASES/init:/init-data:Z
      - ./create-postgres-databases.sh:/create-postgres-databases.sh:Z
      - ./init-databases.sh:/init-databases.sh:Z
      - ./init-geo-data.sh:/init-geo-data.sh:Z
      - ./init-lines-catalog.sh:/init-lines-catalog.sh:Z
    restart: unless-stopped

  postgres-exporter:
    profiles:
      - all
      - metrics
    image: prometheuscommunity/postgres-exporter:v0.15.0
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=postgres
      - DATA_SOURCE_URI=postgres:5432/postgres?sslmode=disable
    restart: unless-stopped
    depends_on:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.10
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - LOGSPOUT=ignore
      - xpack.security.enabled=false
      - ingest.geoip.downloader.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - action.auto_create_index=filebeat-*
    volumes:
      - $GRIDSUITE_DATABASES/elasticsearch:/usr/share/elasticsearch/data
    restart: unless-stopped

  elasticsearch-exporter:
    profiles:
      - all
      - metrics
    image: prometheuscommunity/elasticsearch-exporter:v1.7.0
    command:
      - '--es.uri=http://elasticsearch:9200'
    ports:
      - "9114:9114"
    restart: unless-stopped
    depends_on:
      - elasticsearch

  kibana:
    profiles:
      - all
      - kibana
    image: docker.elastic.co/kibana/kibana:8.19.10
    ports:
      - 5601:5601
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - elasticsearch
    restart: unless-stopped

  logstash:
    profiles:
      - all
      - kibana
    image: docker.elastic.co/logstash/logstash:8.19.10
    volumes:
      - ./pipelines.yml:/config/pipelines.yml:Z
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:Z
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - elasticsearch
    restart: unless-stopped

  socat:
    profiles:
      - all
      - kibana
    image: alpine/socat
    command: 'TCP-LISTEN:5000,reuseaddr,fork TCP:logstash:5000,forever,interval=5'
    restart: unless-stopped

  logspout:
    profiles:
      - all
      - kibana
    image: gliderlabs/logspout:v3.2.13
    command: 'tcp://socat:5000?filter.name=grid*'
    environment:
      - LOGSPOUT=ignore
      - BACKLOG=false
      - "RAW_FORMAT={ \"container\": {{ toJSON .Container.Name }}, \"message\": {{ toJSON .Data }}, \"@timestamp\": {{ toJSON .Time }} }\n"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - socat
    restart: unless-stopped

  pgadmin:
    profiles:
      - all
      - pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "12080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./servers_pgadmin.json:/pgadmin4/servers.json
    restart: unless-stopped

  s3-storage:
    image: minio/minio:RELEASE.2023-09-27T15-22-50Z
    # need to override entrypoint to create the bucket, is there a simpler way ?
    entrypoint: sh
    command: -c 'mkdir -p /data/ws-bucket && /usr/bin/docker-entrypoint.sh server /data --console-address ":19090"'
    ports:
      - "19000:9000"
      - "19090:19090"
    environment:
      - MINIO_ROOT_USER=s3username
      - MINIO_ROOT_PASSWORD=s3password
    volumes:
      - $GRIDSUITE_DATABASES/cases_v1/miniodata:/data:Z
    restart: on-failure

  prometheus:
    profiles:
      - all
      - metrics
    image: prom/prometheus:v3.8.1
    command: --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml:ro
    restart: unless-stopped
    ports:
      - "8000:9090"

  grafana:
    profiles:
      - all
      - metrics
    image: grafana/grafana:11.3.0
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
    ports:
      - "7000:3000"
