apiVersion: v1
kind: Service
metadata:
  labels:
    name: network-modification-server
    app-prometheus-metrics: enabled
    app.kubernetes.io/component: gridsuite-springboot
  name: network-modification-server
spec:
  selector:
    name: network-modification-server
