apiVersion: v1
kind: Service
metadata:
  labels:
    name: shortcircuit-server
    app.kubernetes.io/component: gridsuite-springboot
  name: shortcircuit-server
spec:
  selector:
    name: shortcircuit-server

